export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_SALES_GETDATA = 'FETCH_SALES_GETDATA';
export const FETCH_CUSTOMER_DATA = 'FETCH_CUSTOMER_DATA';
export const FETCH_SALES_SAVEDATA = 'FETCH_SALES_SAVEDATA';
export const FETCH_GETSALES_DATA = 'FETCH_GETSALES_DATA';
export const FETCH_GETSALESITEM_DATA = 'FETCH_GETSALESITEM_DATA';